version: '3.4'
services:
    gcc46:
        build:
            context: gcc_4.6
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc46:${DOCKER_BUILD_TAG}"
        container_name: gcc46
        tty: true
    gcc48:
        build:
            context: gcc_4.8
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc48:${DOCKER_BUILD_TAG}"
        container_name: gcc48
        tty: true
    gcc48-x86:
        build:
            context: gcc_4.8-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc48-x86:${DOCKER_BUILD_TAG}"
        container_name: gcc48-x86
        tty: true
    gcc49:
        build:
            context: gcc_4.9
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc49:${DOCKER_BUILD_TAG}"
        container_name: gcc49
        tty: true
    gcc49-x86:
        build:
            context: gcc_4.9-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc49-x86:${DOCKER_BUILD_TAG}"
        container_name: gcc49-x86
        tty: true
    gcc49-armv7:
        build:
            context: gcc_4.9-armv7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc49-armv7:${DOCKER_BUILD_TAG}"
        container_name: gcc49-armv7
        tty: true
    gcc49-armv7hf:
        build:
            context: gcc_4.9-armv7hf
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc49-armv7hf:${DOCKER_BUILD_TAG}"
        container_name: gcc49-armv7hf
        tty: true
    gcc5:
        build:
            context: gcc_5
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc5:${DOCKER_BUILD_TAG}"
        container_name: gcc5
        tty: true
    gcc5-x86:
        build:
            context: gcc_5-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc5-x86:${DOCKER_BUILD_TAG}"
        container_name: gcc5-x86
        tty: true
    gcc5-armv7:
        build:
            context: gcc_5-armv7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc5-armv7:${DOCKER_BUILD_TAG}"
        container_name: gcc5-armv7
        tty: true
    gcc5-armv7hf:
        build:
            context: gcc_5-armv7hf
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc5-armv7hf:${DOCKER_BUILD_TAG}"
        container_name: gcc5-armv7hf
        tty: true
    gcc52:
        build:
            context: gcc_5.2
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc52:${DOCKER_BUILD_TAG}"
        container_name: gcc52
        tty: true
    gcc53:
        build:
            context: gcc_5.3
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc53:${DOCKER_BUILD_TAG}"
        container_name: gcc53
        tty: true
    gcc54:
        build:
            context: gcc_5.4
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc54:${DOCKER_BUILD_TAG}"
        container_name: gcc54
        tty: true
    gcc6:
        build:
            context: gcc_6
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc6:${DOCKER_BUILD_TAG}"
        container_name: gcc6
        tty: true
    gcc6-x86:
        build:
            context: gcc_6-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc6-x86:${DOCKER_BUILD_TAG}"
        container_name: gcc6-x86
        tty: true
    gcc6-armv7:
        build:
            context: gcc_6-armv7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc6-armv7:${DOCKER_BUILD_TAG}"
        container_name: gcc6-armv7
        tty: true
    gcc6-armv7hf:
        build:
            context: gcc_6-armv7hf
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc6-armv7hf:${DOCKER_BUILD_TAG}"
        container_name: gcc6-armv7hf
        tty: true
    gcc63:
        build:
            context: gcc_6.3
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc63:${DOCKER_BUILD_TAG}"
        container_name: gcc63
        tty: true
    gcc64:
        build:
            context: gcc_6.4
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc64:${DOCKER_BUILD_TAG}"
        container_name: gcc64
        tty: true
    gcc7:
        build:
            context: gcc_7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc7:${DOCKER_BUILD_TAG}"
        container_name: gcc7
        tty: true
    gcc7-x86:
        build:
            context: gcc_7-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc7-x86:${DOCKER_BUILD_TAG}"
        container_name: gcc7-x86
        tty: true
    gcc7-armv7:
        build:
            context: gcc_7-armv7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc7-armv7:${DOCKER_BUILD_TAG}"
        container_name: gcc7-armv7
        tty: true
    gcc7-armv7hf:
        build:
            context: gcc_7-armv7hf
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc7-armv7hf:${DOCKER_BUILD_TAG}"
        container_name: gcc7-armv7hf
        tty: true
    gcc72:
        build:
            context: gcc_7.2
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc72:${DOCKER_BUILD_TAG}"
        container_name: gcc72
        tty: true
    gcc8:
        build:
            context: gcc_8
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc8:${DOCKER_BUILD_TAG}"
        container_name: gcc8
        tty: true
    gcc8-x86:
        build:
            context: gcc_8-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc8-x86:${DOCKER_BUILD_TAG}"
        container_name: gcc8-x86
        tty: true
    gcc8-armv7:
        build:
            context: gcc_8-armv7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc8-armv7:${DOCKER_BUILD_TAG}"
        container_name: gcc8-armv7
        tty: true
    gcc8-armv7hf:
        build:
            context: gcc_8-armv7hf
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/gcc8-armv7hf:${DOCKER_BUILD_TAG}"
        container_name: gcc8-armv7hf
        tty: true
    clang38:
        build:
            context: clang_3.8
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang38:${DOCKER_BUILD_TAG}"
        container_name: clang38
        tty: true
    clang39:
        build:
            context: clang_3.9
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang39:${DOCKER_BUILD_TAG}"
        container_name: clang39
        tty: true
    clang39-x86:
        build:
            context: clang_3.9-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang39-x86:${DOCKER_BUILD_TAG}"
        container_name: clang39-x86
        tty: true
    clang40:
        build:
            context: clang_4.0
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang40:${DOCKER_BUILD_TAG}"
        container_name: clang40
        tty: true
    clang40-x86:
        build:
            context: clang_4.0-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang40-x86:${DOCKER_BUILD_TAG}"
        container_name: clang40-x86
        tty: true
    clang50:
        build:
            context: clang_5.0
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang50:${DOCKER_BUILD_TAG}"
        container_name: clang50
        tty: true
    clang50-x86:
        build:
            context: clang_5.0-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang50-x86:${DOCKER_BUILD_TAG}"
        container_name: clang50-x86
        tty: true
    clang60:
        build:
            context: clang_6.0
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang60:${DOCKER_BUILD_TAG}"
        container_name: clang60
        tty: true
    clang60-x86:
        build:
            context: clang_6.0-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang60-x86:${DOCKER_BUILD_TAG}"
        container_name: clang60-x86
        tty: true
    clang7:
        build:
            context: clang_7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang7:${DOCKER_BUILD_TAG}"
        container_name: clang7
        tty: true
    clang7-x86:
        build:
            context: clang_7-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/clang7-x86:${DOCKER_BUILD_TAG}"
        container_name: clang7-x86
        tty: true
    conan_server:
        build:
            context: conan_server
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conan_server:${DOCKER_BUILD_TAG}"
        container_name: conan_server
    msvc14:
        build:
            context: msvc_14
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/msvc14:${DOCKER_BUILD_TAG}"
        container_name: msvc14
        tty: true
        storage_opt:
          size: '20G'
    msvc15:
        build:
            context: msvc_15
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/msvc15:${DOCKER_BUILD_TAG}"
        container_name: msvc15
        tty: true
        storage_opt:
          size: '20G'
