version: '3'
services:
    conangcc46:
        build:
            context: gcc_4.6
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc46:${DOCKER_BUILD_TAG}"
        container_name: conangcc46
        tty: true
    conangcc48:
        build:
            context: gcc_4.8
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc48:${DOCKER_BUILD_TAG}"
        container_name: conangcc48
        tty: true
    conangcc49:
        build:
            context: gcc_4.9
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc49:${DOCKER_BUILD_TAG}"
        container_name: conangcc49
        tty: true
    conangcc49-x86:
        build:
            context: gcc_4.9-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc49-x86:${DOCKER_BUILD_TAG}"
        container_name: conangcc49-x86
        tty: true
    conangcc49-armv7:
        build:
            context: gcc_4.9-armv7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc49-armv7:${DOCKER_BUILD_TAG}"
        container_name: conangcc49-armv7
        tty: true
    conangcc49-armv7hf:
        build:
            context: gcc_4.9-armv7hf
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc49-armv7hf:${DOCKER_BUILD_TAG}"
        container_name: conangcc49-armv7hf
        tty: true
    conangcc5:
        build:
            context: gcc_5
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc5:${DOCKER_BUILD_TAG}"
        container_name: conangcc5
        tty: true
    conangcc5-x86:
        build:
            context: gcc_5-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc5-x86:${DOCKER_BUILD_TAG}"
        container_name: conangcc5-x86
        tty: true
    conangcc5-armv7:
        build:
            context: gcc_5-armv7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc5-armv7:${DOCKER_BUILD_TAG}"
        container_name: conangcc5-armv7
        tty: true
    conangcc5-armv7hf:
        build:
            context: gcc_5-armv7hf
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc5-armv7hf:${DOCKER_BUILD_TAG}"
        container_name: conangcc5-armv7hf
        tty: true
    conangcc52:
        build:
            context: gcc_5.2
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc52:${DOCKER_BUILD_TAG}"
        container_name: conangcc52
        tty: true
    conangcc53:
        build:
            context: gcc_5.3
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc53:${DOCKER_BUILD_TAG}"
        container_name: conangcc53
        tty: true
    conangcc54:
        build:
            context: gcc_5.4
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc54:${DOCKER_BUILD_TAG}"
        container_name: conangcc54
        tty: true
    conangcc6:
        build:
            context: gcc_6
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc6:${DOCKER_BUILD_TAG}"
        container_name: conangcc6
        tty: true
    conangcc6-x86:
        build:
            context: gcc_6-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc6-x86:${DOCKER_BUILD_TAG}"
        container_name: conangcc6-x86
        tty: true
    conangcc6-armv7:
        build:
            context: gcc_6-armv7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc6-armv7:${DOCKER_BUILD_TAG}"
        container_name: conangcc6-armv7
        tty: true
    conangcc6-armv7hf:
        build:
            context: gcc_6-armv7hf
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc6-armv7hf:${DOCKER_BUILD_TAG}"
        container_name: conangcc6-armv7hf
        tty: true
    conangcc63:
        build:
            context: gcc_6.3
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc63:${DOCKER_BUILD_TAG}"
        container_name: conangcc63
        tty: true
    conangcc64:
        build:
            context: gcc_6.4
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc64:${DOCKER_BUILD_TAG}"
        container_name: conangcc64
        tty: true
    conangcc7:
        build:
            context: gcc_7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc7:${DOCKER_BUILD_TAG}"
        container_name: conangcc7
        tty: true
    conangcc7-x86:
        build:
            context: gcc_7-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc7-x86:${DOCKER_BUILD_TAG}"
        container_name: conangcc7-x86
        tty: true
    conangcc7-armv7:
        build:
            context: gcc_7-armv7
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc7-armv7:${DOCKER_BUILD_TAG}"
        container_name: conangcc7-armv7
        tty: true
    conangcc7-armv7hf:
        build:
            context: gcc_7-armv7hf
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc7-armv7hf:${DOCKER_BUILD_TAG}"
        container_name: conangcc7-armv7hf
        tty: true
    conangcc72:
        build:
            context: gcc_7.2
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc72:${DOCKER_BUILD_TAG}"
        container_name: conangcc72
        tty: true
    conangcc8:
        build:
            context: gcc_8
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc8:${DOCKER_BUILD_TAG}"
        container_name: conangcc8
        tty: true
    conanclang38:
        build:
            context: clang_3.8
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conanclang38:${DOCKER_BUILD_TAG}"
        container_name: conanclang38
        tty: true
    conanclang39:
        build:
            context: clang_3.9
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conanclang39:${DOCKER_BUILD_TAG}"
        container_name: conanclang39
        tty: true
    conanclang39-x86:
        build:
            context: clang_3.9-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conanclang39-x86:${DOCKER_BUILD_TAG}"
        container_name: conanclang39-x86
        tty: true
    conanclang40:
        build:
            context: clang_4.0
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conanclang40:${DOCKER_BUILD_TAG}"
        container_name: conanclang40
        tty: true
    conanclang40-x86:
        build:
            context: clang_4.0-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conanclang40-x86:${DOCKER_BUILD_TAG}"
        container_name: conanclang40-x86
        tty: true
    conanclang50:
        build:
            context: clang_5.0
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conanclang50:${DOCKER_BUILD_TAG}"
        container_name: conanclang50
        tty: true
    conanclang50-x86:
        build:
            context: clang_5.0-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conanclang50-x86:${DOCKER_BUILD_TAG}"
        container_name: conanclang50-x86
        tty: true
    conanclang60:
        build:
            context: clang_6.0
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conanclang60:${DOCKER_BUILD_TAG}"
        container_name: conanclang60
        tty: true
    conanclang60-x86:
        build:
            context: clang_6.0-x86
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conanclang60-x86:${DOCKER_BUILD_TAG}"
        container_name: conanclang60-x86
        tty: true
    conan_server:
        build:
            context: conan_server
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conan_server:${DOCKER_BUILD_TAG}"
        container_name: conan_server
