name: 'conan-docker-tools-modern'

x-common-args: &common-args
    CMAKE_VERSION: ${CMAKE_VERSION}
    PYTHON_VERSION: ${PYTHON_VERSION}
    CONAN_VERSION: ${CONAN_VERSION}
    LIBSTDCPP_VERSION: ${LIBSTDCPP_VERSION}
    LIBSTDCPP_PATCH_VERSION: ${LIBSTDCPP_PATCH_VERSION}
    DOCKER_USERNAME: ${DOCKER_USERNAME}
    DOCKER_TAG: ${DOCKER_TAG}
    DISTRO: ${DISTRO}
    DISTRO_VERSION: ${DISTRO_VERSION}

x-gcc11: &gcc11
    GCC_VERSION: ${GCC11_VERSION}

x-llvm13: &llvm13
    CLANG_VERSION: ${CLANG13_VERSION}

services:
    # Base image
    base:
        platform: ${PLATFORM}
        build:
            context: base
            dockerfile: Dockerfile
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/base-${DISTRO}:${DOCKER_TAG}
        container_name: base
        tty: true

    gcc11-builder:
        platform: ${PLATFORM}
        build:
            context: gcc
            dockerfile: Dockerfile
            target: builder
            args:
                <<: [*common-args, *gcc11]
        image: ${DOCKER_USERNAME}/gcc11-builder-${DISTRO}:${DOCKER_TAG}
        container_name: gcc11-builder
        tty: true

    clang13-builder:
        platform: ${PLATFORM}
        build:
            context: clang
            dockerfile: Dockerfile
            target: clang-builder
            args:
                <<: [*common-args, *llvm13]
        image: ${DOCKER_USERNAME}/clang13-builder-${DISTRO}:${DOCKER_TAG}
        container_name: clang13-builder
        tty: true

    gcc11-deploy:
        platform: ${PLATFORM}
        build:
            context: gcc
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/gcc11-builder-${DISTRO}:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/gcc11-deploy-${DISTRO}:${DOCKER_TAG}
        container_name: gcc11-deploy
        tty: true

    clang13-deploy:
        platform: ${PLATFORM}
        build:
            context: clang
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/clang13-builder-${DISTRO}:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/clang13-deploy-${DISTRO}:${DOCKER_TAG}
        container_name: clang13-deploy
        tty: true

    gcc11:
        platform: ${PLATFORM}
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                <<: [*common-args, *gcc11]
        image: ${DOCKER_USERNAME}/gcc11-${DISTRO}:${DOCKER_TAG}
        container_name: gcc11
        tty: true

    clang13:
        platform: ${PLATFORM}
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                <<: [*common-args, *llvm13]
        image: ${DOCKER_USERNAME}/clang13-${DISTRO}:${DOCKER_TAG}
        container_name: clang13
        tty: true

    gcc11-jenkins:
        platform: ${PLATFORM}
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc11-${DISTRO}:${DOCKER_TAG}
                JENKINS_AGENT_VERSION: ${JENKINS_AGENT_VERSION}
                JAVA_JDK_VERSION: ${JAVA_JDK_VERSION}
                <<: *common-args
        image: "${DOCKER_USERNAME}/gcc11-${DISTRO}-jenkins:${DOCKER_TAG}-${JENKINS_AGENT_VERSION}"
        container_name: gcc11-jenkins

    clang13-jenkins:
        platform: ${PLATFORM}
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/clang13-${DISTRO}:${DOCKER_TAG}
                JENKINS_AGENT_VERSION: ${JENKINS_AGENT_VERSION}
                JAVA_JDK_VERSION: ${JAVA_JDK_VERSION}
                <<: *common-args
        image: "${DOCKER_USERNAME}/clang13-${DISTRO}-jenkins:${DOCKER_TAG}-${JENKINS_AGENT_VERSION}"
        container_name: clang13-jenkins
