version: '3.4'

x-common-args: &common-args
    CMAKE_VERSION_FULL: ${CMAKE_VERSION_FULL}
    CMAKE_VERSION: ${CMAKE_VERSION}
    PYTHON_VERSION: ${PYTHON_VERSION}
    CONAN_VERSION: ${CONAN_VERSION}
    LIBSTDCPP_VERSION: ${LIBSTDCPP_VERSION}
    LIBSTDCPP_PATCH_VERSION: ${LIBSTDCPP_PATCH_VERSION}
    DOCKER_USERNAME: ${DOCKER_USERNAME}
    ARTIFACTORY_REPOSITORY: ${ARTIFACTORY_REPOSITORY:-https://c3istg.jfrog.io/artifactory/dad-generic}
    JENKINS_AGENT_VERSION: ${JENKINS_AGENT_VERSION:-3.27}
    DOCKER_TAG: ${DOCKER_TAG}

x-gcc5: &gcc5
    GCC_VERSION: 5.5.0

x-gcc6: &gcc6
    GCC_VERSION: 6.5.0

x-gcc7: &gcc7
    GCC_VERSION: 7.5.0

x-gcc8: &gcc8
    GCC_VERSION: 8.4.0

x-gcc9: &gcc9
    GCC_VERSION: 9.3.0

x-gcc10: &gcc10
    GCC_VERSION: 10.3.0

x-gcc11: &gcc11
    GCC_VERSION: 11.1.0

x-llvm10: &llvm10
    LLVM_VERSION: 10.0.1

x-llvm11: &llvm11
    LLVM_VERSION: 11.1.0

x-llvm12: &llvm12
    LLVM_VERSION: 12.0.0


services:
    # Base image
    base:
        build:
            context: base
            dockerfile: Dockerfile
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/base-ubuntu16.04:${DOCKER_TAG}
        container_name: base
        tty: true

    # Builder images
    gcc5-builder:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: gcc-builder
            args:
                <<: *common-args
                <<: *gcc5
        image: ${DOCKER_USERNAME}/gcc5-builder-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc5-builder
        tty: true
    gcc6-builder:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: gcc-builder
            args:
                <<: *common-args
                <<: *gcc6
        image: ${DOCKER_USERNAME}/gcc6-builder-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc6-builder
        tty: true
    gcc7-builder:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: gcc-builder
            args:
                <<: *common-args
                <<: *gcc7
        image: ${DOCKER_USERNAME}/gcc7-builder-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc7-builder
        tty: true
    gcc8-builder:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: gcc-builder
            args:
                <<: *common-args
                <<: *gcc8
        image: ${DOCKER_USERNAME}/gcc8-builder-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc8-builder
        tty: true
    gcc9-builder:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: gcc-builder
            args:
                <<: *common-args
                <<: *gcc9
        image: ${DOCKER_USERNAME}/gcc9-builder-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc9-builder
        tty: true
    gcc10-builder:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: gcc-builder
            args:
                <<: *common-args
                <<: *gcc10
        image: ${DOCKER_USERNAME}/gcc10-builder-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc10-builder
        tty: true
    gcc11-builder:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: gcc-builder
            args:
                <<: *common-args
                <<: *gcc11
        image: ${DOCKER_USERNAME}/gcc11-builder-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc11-builder
        tty: true
    clang10-builder:
        build:
            context: clang
            dockerfile: Dockerfile
            target: clang-builder
            args:
                <<: *common-args
                <<: *llvm10
        image: ${DOCKER_USERNAME}/clang10-builder-ubuntu16.04:${DOCKER_TAG}
        container_name: clang10-builder
        tty: true
    clang11-builder:
        build:
            context: clang
            dockerfile: Dockerfile
            target: clang-builder
            args:
                <<: *common-args
                <<: *llvm11
        image: ${DOCKER_USERNAME}/clang11-builder-ubuntu16.04:${DOCKER_TAG}
        container_name: clang11-builder
        tty: true
    clang12-builder:
        build:
            context: clang
            dockerfile: Dockerfile
            target: clang-builder
            args:
                <<: *common-args
                <<: *llvm12
        image: ${DOCKER_USERNAME}/clang12-builder-ubuntu16.04:${DOCKER_TAG}
        container_name: clang12-builder
        tty: true

    # Deploy images
    gcc5-deploy:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/gcc5-builder-ubuntu16.04:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/gcc5-deploy-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc5-deploy
        tty: true
    gcc6-deploy:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/gcc6-builder-ubuntu16.04:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/gcc6-deploy-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc6-deploy
        tty: true
    gcc7-deploy:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/gcc7-builder-ubuntu16.04:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/gcc7-deploy-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc7-deploy
        tty: true
    gcc8-deploy:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/gcc8-builder-ubuntu16.04:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/gcc8-deploy-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc8-deploy
        tty: true
    gcc9-deploy:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/gcc9-builder-ubuntu16.04:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/gcc9-deploy-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc9-deploy
        tty: true
    gcc10-deploy:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/gcc10-builder-ubuntu16.04:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/gcc10-deploy-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc10-deploy
        tty: true
    gcc11-deploy:
        build:
            context: gcc
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/gcc11-builder-ubuntu16.04:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/gcc11-deploy-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc11-deploy
        tty: true
    clang10-deploy:
        build:
            context: clang
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/clang10-builder-ubuntu16.04:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/clang10-deploy-ubuntu16.04:${DOCKER_TAG}
        container_name: clang10-deploy
        tty: true
    clang11-deploy:
        build:
            context: clang
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/clang11-builder-ubuntu16.04:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/clang11-deploy-ubuntu16.04:${DOCKER_TAG}
        container_name: clang11-deploy
        tty: true
    clang12-deploy:
        build:
            context: clang
            dockerfile: Dockerfile
            target: deploy
            cache_from:
              - ${DOCKER_USERNAME}/clang12-builder-ubuntu16.04:${DOCKER_TAG}
            args:
                <<: *common-args
        image: ${DOCKER_USERNAME}/clang12-deploy-ubuntu16.04:${DOCKER_TAG}
        container_name: clang12-deploy
        tty: true

    # Images
    gcc5:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                <<: *common-args
                <<: *gcc5
        image: ${DOCKER_USERNAME}/gcc5-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc5
        tty: true
    gcc6:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                <<: *common-args
                <<: *gcc6
        image: ${DOCKER_USERNAME}/gcc6-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc6
        tty: true
    gcc7:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                <<: *common-args
                <<: *gcc7
        image: ${DOCKER_USERNAME}/gcc7-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc7
        tty: true
    gcc8:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                <<: *common-args
                <<: *gcc8
        image: ${DOCKER_USERNAME}/gcc8-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc8
        tty: true
    gcc9:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                <<: *common-args
                <<: *gcc9
        image: ${DOCKER_USERNAME}/gcc9-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc9
        tty: true
    gcc10:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                <<: *common-args
                <<: *gcc10
        image: ${DOCKER_USERNAME}/gcc10-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc10
        tty: true
    gcc11:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                <<: *common-args
                <<: *gcc11
        image: ${DOCKER_USERNAME}/gcc11-ubuntu16.04:${DOCKER_TAG}
        container_name: gcc11
        tty: true
    clang10:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                <<: *common-args
                <<: *llvm10
        image: ${DOCKER_USERNAME}/clang10-ubuntu16.04:${DOCKER_TAG}
        container_name: clang10
        tty: true
    clang11:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                <<: *common-args
                <<: *llvm11
        image: ${DOCKER_USERNAME}/clang11-ubuntu16.04:${DOCKER_TAG}
        container_name: clang11
        tty: true
    clang12:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                <<: *common-args
                <<: *llvm12
        image: ${DOCKER_USERNAME}/clang12-ubuntu16.04:${DOCKER_TAG}
        container_name: clang12
        tty: true

    # Jenkins images
    gcc5-jenkins:
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc5-ubuntu16.04:${DOCKER_TAG}
                <<: *common-args
        image: "${DOCKER_USERNAME}/gcc5-ubuntu16.04-jenkins:${DOCKER_TAG}"
        container_name: gcc5-jenkins
    gcc6-jenkins:
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc6-ubuntu16.04:${DOCKER_TAG}
                <<: *common-args
        image: "${DOCKER_USERNAME}/gcc6-ubuntu16.04-jenkins:${DOCKER_TAG}"
        container_name: gcc6-jenkins
    gcc7-jenkins:
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc7-ubuntu16.04:${DOCKER_TAG}
                <<: *common-args
        image: "${DOCKER_USERNAME}/gcc7-ubuntu16.04-jenkins:${DOCKER_TAG}"
        container_name: gcc7-jenkins
    gcc8-jenkins:
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc8-ubuntu16.04:${DOCKER_TAG}
                <<: *common-args
        image: "${DOCKER_USERNAME}/gcc8-ubuntu16.04-jenkins:${DOCKER_TAG}"
        container_name: gcc8-jenkins
    gcc9-jenkins:
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc9-ubuntu16.04:${DOCKER_TAG}
                <<: *common-args
        image: "${DOCKER_USERNAME}/gcc9-ubuntu16.04-jenkins:${DOCKER_TAG}"
        container_name: gcc9-jenkins
    gcc10-jenkins:
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc10-ubuntu16.04:${DOCKER_TAG}
                <<: *common-args
        image: "${DOCKER_USERNAME}/gcc10-ubuntu16.04-jenkins:${DOCKER_TAG}"
        container_name: gcc10-jenkins
    gcc11-jenkins:
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/gcc11-ubuntu16.04:${DOCKER_TAG}
                <<: *common-args
        image: "${DOCKER_USERNAME}/gcc11-ubuntu16.04-jenkins:${DOCKER_TAG}"
        container_name: gcc11-jenkins
    clang10-jenkins:
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/clang10-ubuntu16.04:${DOCKER_TAG}
                <<: *common-args
        image: "${DOCKER_USERNAME}/clang10-ubuntu16.04-jenkins:${DOCKER_TAG}"
        container_name: clang10-jenkins
    clang11-jenkins:
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/clang11-ubuntu16.04:${DOCKER_TAG}
                <<: *common-args
        image: "${DOCKER_USERNAME}/clang11-ubuntu16.04-jenkins:${DOCKER_TAG}"
        container_name: clang11-jenkins
    clang12-jenkins:
        build:
            context: jenkins
            dockerfile: Dockerfile
            args:
                SOURCE_CONANIO_IMAGE: ${DOCKER_USERNAME}/clang12-ubuntu16.04:${DOCKER_TAG}
                <<: *common-args
        image: "${DOCKER_USERNAME}/clang12-ubuntu16.04-jenkins:${DOCKER_TAG}"
        container_name: clang12-jenkins
